#! /usr/bin/python

import argparse

from skymodel import get_beam, parsers


def main():

    description = """
    Create a FITS image of the psuedo-Stokes I primary beam response.
    """

    ps = argparse.ArgumentParser(description=description)
    ps.add_argument("metafits", help="A metafits file for a given observation.")
    ps.add_argument("-o", "--outname", help="Output FITS file name.")
    ps.add_argument("-p", "--plot", action="store_true", 
                    help="Make a plot of the FITS file.")
    ps.add_argument("-c", "--cmap", help="Colormap to use when plotting.")

    args = ps.parse_args()

    if args.outname is None:
        args.outname = args.metafits.replace(".metafits", "_beamI.fits")


    t, delays, freq, _ = parsers.parse_metafits(args.metafits)

    get_beam.make_beam_image(t, delays, freq, args.outname,
                             cmap=args.cmap, plot=args.plot)

    