#! /usr/bin/env python

import argparse


def line_formatter(ra, dec, a, b, pa):
    """Format a line for the region file."""
    return "ellipse {}d {}d {}\" {}\" {}d\n".format(ra, dec, a, b, pa)


def main():
        
    description = """
    Create a ds9 region file from a skymodel .csv file.
    """

    ps = argparse.ArgumentParser(description=description)
    ps.add_argument("infile")
    ps.add_argument("-m", "--marker", default="cross", type=str)
    ps.add_argument("-c", "--color", default="green", type=str)

    args = ps.parse_args()

    outname = args.infile.replace(".csv", ".reg")

    with open(outname, "w+") as f:
        f.write("# Region file format: DS9 version 4.1\n")
        f.write("global color={}\n".format(args.color))
        f.write("fk5\n")

        with open(args.infile, "r") as g:
            lines = g.readlines()
            for line in lines:
                if "RA" not in line:
                    bits = line.split(",")
                    f.write(line_formatter(*bits[:-1]))






if __name__ == "__main__":
    main()