#! /usr/bin/env python

import argparse

from astropy.io import fits
from astropy.coordinates import SkyCoord
from astropy import units as u
from skymodel import get_beam, parsers


def main():

    description = """
    Find the location and approximate size of the lobes of the MWA primary 
    beam. Note that the mainlobe is return as the first lobe.
    """

    ps = argparse.ArgumentParser(description=description)
    ps.add_argument("image", help="Image of the psuedo-Stokes I beam.")
    ps.add_argument("-p", "--perc", type=float, default=0.1,
                    help="Percentage of attenuation out to which determines "
                         "the size of the primary beam. [Default 0.1]")
    ps.add_argument("-m", "--metafits", action="store_true",
                    help="Supply a metafits file to make a primary beam image. "
                         "If this option is used the positional argument should "
                         "be the metafits file.")
    ps.add_argument("-S", "--sidelobes", action="store_true",
                    help="Switch to return only the sidelobes.")
    ps.add_argument("-M", "--mainlobe", action="store_true",
                    help="Switch to return only the mainlobe.")

    args = ps.parse_args()

    if args.sidelobes and args.mainlobe:
        return RuntimeError("No lobes to find!")

    if args.metafits:

        t, delays, freq, pnt = parsers.parse_metafits(args.image)
        hdu = get_beam.make_beam_image(t, delays, freq, 
                                       ra=pnt.ra.value,
                                       return_hdu=True)

    else:

        hdu = fits.open(args.image)[0]


    lobes = get_beam.find_lobes(hdu, perc=args.perc)

    if args.metafits:
        min_sep = 1e9
        for i in lobes.keys():
            coords = SkyCoord(ra=lobes[i].ra,
                              dec=lobes[i].dec,
                              unit=(u.deg, u.deg))
            sep = coords.separation(pnt)
            if sep.value < min_sep:
                min_sep = sep.value
                main_lobe = i
    else:
        main_lobe = 1


    if not args.sidelobes:
        # Main lobe:
        print("main: {:.2f} {:+.2f} {:.2f}".format(lobes[main_lobe].ra, 
                                                   lobes[main_lobe].dec, 
                                                   lobes[main_lobe].maximum_size))
    if not args.mainlobe:
        for i in lobes.keys():
            if i != main_lobe:
                print("side: {:.2f} {:+.2f} {:.2f}".format(lobes[i].ra,
                                                           lobes[i].dec,
                                                           lobes[i].maximum_size))


if __name__ == "__main__":
    main()