#! /usr/bin/env python

import argparse

from skymodel import get_beam, parsers


# TODO plotting

def main():

    description = """
    Create a FITS image of the psuedo-Stokes I primary beam response.
    """

    ps = argparse.ArgumentParser(description=description)
    ps.add_argument("metafits", help="A metafits file for a given observation.")
    ps.add_argument("-o", "--outname", help="Output FITS file name.")
    ps.add_argument("-p", "--plot", action="store_true", 
                    help="Make a plot of the FITS file.")
    ps.add_argument("-c", "--cmap", help="Colormap to use when plotting.")
    ps.add_argument("-i", "--image", default=None)
    ps.add_argument("-f", "--frequency", dest="freq", default=None, type=float)

    args = ps.parse_args()

    if args.outname is None:
        args.outname = args.metafits.replace(".metafits", "_beamI.fits")


    t, delays, freq, pnt = parsers.parse_metafits(args.metafits)
    if args.freq is not None:
        freq = args.freq

    get_beam.make_beam_image(t, delays, freq, 
                             ra=pnt.ra.value,
                             outname=args.outname,
                             cmap=args.cmap, 
                             plot=args.plot,
                             reference_image=args.image)

    

if __name__ == "__main__":
    main()