#! /usr/bin/env python

from argparse import ArgumentParser
from skymodel.model_flux import prep_model


def main():

    ps = ArgumentParser()
    ps.add_argument("-d", "--dir", dest="dir", default="./")
    ps.add_argument("-m", "--metafits", dest="metafits", default=None, 
                        help="MWA metafits file to read frequency from.")
    ps.add_argument("-t", "--threshold", dest="threshold", default=2., type=float)
    ps.add_argument("-o", "--outname", dest="outname", default="all_models.txt")

    args = ps.parse_args()

    if (args.metafits is None):
        raise ValueError("A metafits file must be supplied.")

    prep_model(indir=args.dir,
               metafits=args.metafits,
               threshold=args.threshold,
               outname=args.outname)


if __name__ == "__main__":
    main()