#! /usr/bin/env python

from argparse import ArgumentParser
from skymodel.model_flux import prep_model


def main():

    help_ = {"d": ""}

    ps = ArgumentParser()
    ps.add_argument("-d", "--dir", dest="dir", default=None)
    ps.add_argument("-i", "--input", dest="input", nargs="*")
    ps.add_argument("-m", "--metafits", dest="metafits", default=None, 
                        help="MWA metafits file to read frequency from.")
    ps.add_argument("-t", "--threshold", dest="threshold", default=2., type=float)
    ps.add_argument("-o", "--outname", dest="outname", default="all_models.txt")
    ps.add_argument("-p", "--prefix", dest="prefix", default="model")
    ps.add_argument("-x", "--exclude", dest="exclude", default=None, nargs="*")
    ps.add_argument("-C", "--curved", dest="curved", action="store_true",
                    help="Switch on if wanting to use a curved power law model "
                         "for estimating the flux density of sources.")
    ps.add_argument("-r", "--radius", dest="radius", default=360., type=float,
                    help="Radius within which to include sources. [Default 360 deg]")

    args = ps.parse_args()

    if (args.metafits is None):
        raise ValueError("A metafits file must be supplied.")

    if args.dir is not None:
        inp = args.dir
    else:
        inp = args.input


    prep_model(inp=inp,
               metafits=args.metafits,
               threshold=args.threshold,
               outname=args.outname, 
               prefix=args.prefix,
               exclude=args.exclude,
               curved=args.curved,
               radius=args.radius)

if __name__ == "__main__":
    main()